{% set version = "0.1.7" %}

package:
  name: yaml
  version: {{ version }}

source:
  fn: yaml-{{ version }}.tar.gz
  url: http://pyyaml.org/download/libyaml/yaml-{{ version }}.tar.gz
  sha256: 8088e457264a98ba451a90b8661fcb4f9d6f478f7265d48322a196cec2480729
  patches:
    # Change CMakeLists so that we can build static and shared libraries.
    # See this PR ( https://github.com/yaml/libyaml/pull/10 ) for details.
    - CMakeLists.txt.patch

build:
  number: 0
  features:
    - vc9                # [win and py27]
    - vc10               # [win and py34]
    - vc14               # [win and py35]

requirements:
  build:
    - cmake              # [win]
    - python             # [win]
    - pkg-config         # [unix]
    - libtool            # [unix]

test:
  requires:
    - python {{ environ['PY_VER'] + '*' }}            # [win]

  commands:
    # Check headers.
    - test -f "${PREFIX}/include/yaml.h"              # [unix]
    - if not exist %LIBRARY_INC%\\yaml.h exit 1       # [win]

    # Check libraries.
    - test -f "${PREFIX}/lib/libyaml.a"               # [unix]
    - test -f "${PREFIX}/lib/libyaml.dylib"           # [osx]
    - test -f "${PREFIX}/lib/libyaml.so"              # [linux]
    - if not exist %LIBRARY_LIB%\\yaml_static.lib exit 1     # [win]
    - if not exist %LIBRARY_LIB%\\yaml.lib exit 1     # [win]
    - if not exist %LIBRARY_BIN%\\yaml.dll exit 1     # [win]

about:
  home: http://pyyaml.org/wiki/LibYAML'
  license: MIT
  summary: A C library for parsing and emitting YAML.

extra:
  recipe-maintainers:
    - jakirkham
    - msarahan
    - pelson
